---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: macosx-10.9

suites:
  - name: default
    run_list:
      - recipe[dmg]
  - name: package_install
    run_list:
      - recipe[dmg_test::package_install]
    attributes:
  - name: package_upgrade
    run_list:
      - recipe[dmg_test::package_upgrade]
    attributes:
  - name: package_uninstall
    run_list:
      - recipe[dmg_test::package_remove]
